#!/usr/bin/env ruby

## Pull Requestでは実行しない
pr_env = ENV['SD_PULL_REQUEST']
return puts "Skip release: SD_PULL_REQUEST #{pr_env}" if !pr_env.nil? && !pr_env.empty?

## Build version (Patch version) のアップデート
require 'fileutils'

version_file_path = File.expand_path('../../version', __FILE__)
current_version = if File.exist?(version_file_path) && (version = File.read(version_file_path)) != ''
                    version.to_i
                  else
                    0
                  end

puts "Current build version: #{current_version}"

next_version = current_version + 1

File.write(version_file_path, next_version)

`git add #{version_file_path}`
`git commit -m "[skip ci] Bump build version: #{next_version}"`
`git push origin HEAD:master`
